// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYFlFNObqZstGohQbs5RxGhhvwMd-u0sM',
    appId: '1:591052958411:web:ecd2a48e3ee3cd984d094e',
    messagingSenderId: '591052958411',
    projectId: 'authentication-88022',
    authDomain: 'authentication-88022.firebaseapp.com',
    storageBucket: 'authentication-88022.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOlSaXfxvuuqMlosb9kOhdwwoiL7gSytM',
    appId: '1:591052958411:android:df43fe16920edb6c4d094e',
    messagingSenderId: '591052958411',
    projectId: 'authentication-88022',
    storageBucket: 'authentication-88022.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyTJzcxL8jqflJJJpBnCcFS62v9Ru7iNI',
    appId: '1:591052958411:ios:97fba506da00412f4d094e',
    messagingSenderId: '591052958411',
    projectId: 'authentication-88022',
    storageBucket: 'authentication-88022.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );
}
